name: time_spent
description: Track the time you spend on projects.
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.10.11
  equatable:
  flutter_bloc: ^6.1.2
  intl:
  moor:
  path: ^1.7.0
  path_provider: ^1.6.27
  provider: ^4.3.3
  sqlite3_flutter_libs: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  moor_generator:
  pedantic:


flutter:
  uses-material-design: true
