name: time_spent
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moor: ^2.4.2
  moor_ffi: ^0.4.0
  path: ^1.6.4
  path_provider: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  moor_generator: ^2.4.0


flutter:
  uses-material-design: true
