name: time_spent
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bloc: ^3.0.0
  equatable: ^1.0.0
  fl_chart: ^0.8.7
  flushbar: <1.9.1
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  intl: ^0.16.1
  moor: ^2.4.2
  moor_ffi: ^0.4.0
  path: ^1.6.4
  path_provider: ^1.6.5
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  moor_generator: ^2.4.0


flutter:
  uses-material-design: true
